server:
  port: 8080
  servlet:
    context-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://syh80883.cafe24.com/syh80883
    username: syh80883
    password: abc123!@

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

logging:
  level:
    com.app: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: 5cb00604264a9df18fa52392f86a6af9
    secret: DI307ZiQHDYpAjEZRCfprmuv86KgyTV4

token:
  secret: ENC(9c9uJh1XDJMe72tcz8o94Z1pqQxRrUdKaxFAlScPFuIGZtp57tFR3Q==)
  access-token-expiration-time: 900000
  refresh-token-expiration-time: 1209600000

jasypt:
  password: ${PASSWORD}