spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://syh80883.cafe24.com/syh80883
    username: syh80883
    password: abc123!@